#define PREFIX mawii
#define MAINPREFIX k

#include "script_version.hpp"
#define VERSION         MAJOR.MINOR
#define VERSION_STR     MAJOR.MINOR.PATCH.BUILD
#define VERSION_AR      MAJOR,MINOR,PATCH,BUILD
#define VERSION_PLUGIN  MAJOR.MINOR.PATCH.BUILD

#define REQUIRED_VERSION 2.16

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(DUI - COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(DUI - COMPONENT)
#endif