name: HEMTT

on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT
        run: hemtt release
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with: 
          name: "@mawii"
          path: ".hemttout/release/*"   
          include-hidden-files: true # Because .hemttout is a hidden directory