name: HEMTT

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT build
        run: hemtt release
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with: 
          name: "@mawii"
          path: .hemttout/release/@*
          include-hidden-files: true # Because .hemttout is a hidden directory