name: HEMTT

on:
  push:
    tags:
      "v*.*.*.*"
    branches:
    - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Check for BOM
        uses: arma-actions/bom-check@master  

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT build
        run: hemtt release
      - name: Upload Release
        id: upload_release
        uses: actions/upload-artifact@v4
        with: 
          name: "@mawii"
          path: ".hemttout/release/*"
          include-hidden-files: true # Because .hemttout is a hidden directory
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: MAWII ${{ github.ref_name }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ".hemttout/release/*"
          asset_name: "@mawii.zip"
          asset_content_type: application/zip