name: HEMTT

on:
  push:
    branches:
    - master
  pull_request_target:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT
        run: hemtt release
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with: 
          name: mawii-latest
          path: releases/mawii.zip