name: HEMTT

on:
  push:
    tags:
      "v*.*.*.*"
    branches:
    - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Check for BOM
        uses: arma-actions/bom-check@master  

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master

      - name: Bump Version
        id: bump_version
        run: python3 python_code/version_bumper.py increment_patch push_commit

      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Run HEMTT build
        run: hemtt release

      - name: Upload Release
        id: upload_release
        uses: actions/upload-artifact@v4
        with: 
          name: "mawii"
          path: ".hemttout/release/*"
          include-hidden-files: true # Because .hemttout is a hidden directory
    outputs:
      VERSION: ${{ steps.bump_version.outputs.VERSION }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: release_url
      
      - name: Get Release File Name & Upload URL
        id: get_release_info
        shell: bash
        run: |
            value=`cat release_url/release_url.txt`
            echo ::set-output name=upload_url::$value   
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: mawii-v${{ needs.build.outputs.VERSION }}
          tag_name: ${{ needs.build.outputs.VERSION }}
          #draft: false
          #prerelease: false
      
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ./dist/mawii.zip
          asset_name: "@mawii"
          asset_content_type: application/zip
